/*
 * HelpInfoXNC.java
 *
 *
 * @author Kersten Tams Copyright 2009-2018
 * @author Lothar Roth  Copyright 2012-2018
 *
 */

package my.CVNavi;

import javax.swing.ImageIcon;

/**
 *
 * @author lroth
 */
public class HelpInfoXNC extends javax.swing.JDialog {

    private MC myParent = null;
    /**
     * Creates new form helpLokControl
     */
    public HelpInfoXNC(MC parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if( parent == null ) {
            return;
        }
        if( parent.frameInstanceHelpXNC != null ) {
            parent.frameInstanceHelpXNC.toFront();
            parent.frameInstanceHelpXNC.repaint();
            return;
        }
        parent.frameInstanceHelpXNC = this;
        setLocationRelativeTo(parent);
        myParent = parent;

        // set to top to avoid scrolling to bottom
        this.jTextPane1.setCaretPosition(0);

        ImageIcon Img1 = new ImageIcon(getClass().getResource("/Update_XNControl_small.png"));
        jBild1.setIcon(Img1);
        pack();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpXNCclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jBild1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("XNControl");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpXNCclose.setText("Schließen");
        helpXNCclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpXNCcloseActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setText("<html>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>XNControl für Updates vorbereiten:</b><br>\n      <br>\n      Trennen Sie <b>alle</b> externen Steuergeräte vom EasyNet - einschließlich des XNControl, bei dem Sie ein Update ausführen wollen.<br>\n      Schrauben Sie den Deckel des Gehäuses ab.<br>\n      <br>\n      Überbrücken Sie dann die beiden Pins der Stiftleiste JP1 des XNControl (z.B. mit dem beiliegenden Jumper) und stellen Sie die Verbindung des XNControl zum EasyNet wieder her.<br>\n      <br>\n      Wechseln Sie als nächstes an der MasterControl in den Menüpunkt \"Software-Update\" und bestätigen Sie die Auswahl mit [#] / ok.<br>\n      Im Display der MasterControl erscheint daraufhin in der unteren Zeile \"...Download...\"<br>\n      <br>\n      Wählen Sie in CV-Navi die Datei zum Update des XNControl. Der Dateiname beginnt mit <b>xpressnet110</b><br>\n      <br>\n      Führen Sie das Update durch<br>\n      <br>\n      Danach die Verbindung zum EasyNet wieder trennen, den Jumper wieder entfernen und das Gehäuse wieder schließen.<br>\n    </p>\n  </body>\n</html>\n");
        jScrollPane2.setViewportView(jTextPane1);

        jBild1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBild1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(helpXNCclose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBild1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpXNCclose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpXNCcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpXNCcloseActionPerformed
        if( myParent != null ) {
            myParent.frameInstanceHelpXNC = null;
        }
        this.dispose();
    }//GEN-LAST:event_helpXNCcloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if( myParent != null ) {
            myParent.frameInstanceHelpXNC = null;
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpXNCclose;
    private javax.swing.JLabel jBild1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
