/*
 * HelpInfoPC.java
 *
 *
 * @author Kersten Tams Copyright 2009-2018
 * @author Lothar Roth  Copyright 2012-2018
 *
 */

package my.CVNavi;

import javax.swing.ImageIcon;

/**
 *
 * @author lroth
 */
public class HelpInfoPC extends javax.swing.JDialog {

    private MC myParent = null;
    /**
     * Creates new form helpLokControl
     */
    public HelpInfoPC(MC parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if( parent == null ) {
            return;
        }
        if( parent.frameInstanceHelpPC != null ) {
            parent.frameInstanceHelpPC.toFront();
            parent.frameInstanceHelpPC.repaint();
            return;
        }
        parent.frameInstanceHelpPC = this;
        setLocationRelativeTo(parent);
        myParent = parent;

        // set to top to avoid scrolling to bottom
        this.jTextPane1.setCaretPosition(0);

        ImageIcon Img1 = new ImageIcon(getClass().getResource("/Update_PhoneControl_small.jpg"));
        ImageIcon Img2 = new ImageIcon(getClass().getResource("/Update_PhoneControl_foto_small.jpg"));
        jBild1.setIcon(Img1);
        jBild2.setIcon(Img2);
        pack();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpPCclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jBild1 = new javax.swing.JLabel();
        jBild2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PhoneControl");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpPCclose.setText("Schließen");
        helpPCclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpPCcloseActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setText("<html>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>PhoneControl für Updates vorbereiten:</b><br>\n      <br>\n      Trennen Sie <b>alle</b> externen Steuergeräte vom EasyNet - einschließlich des PhoneControl, bei der Sie ein Update ausführen wollen.<br>\n      Schrauben Sie den Deckel des Gehäuses ab.<br>\n      <br>\n      Überbrücken Sie dann entsprechend dem Foto die Pins der Stiftleisten JP2 an der PhoneControl mit den beiden bei JP3 geliehenen Jumpern und stellen Sie die Verbindung des PhoneControl zum EasyNet wieder her.<br>\n      <br>\n      Wechseln Sie als nächstes an der MasterControl in den Menüpunkt \"Software-Update\" und bestätigen Sie die Auswahl mit [#] / ok.<br>\n      Im Display der MasterControl erscheint daraufhin in der unteren Zeile \"...Download...\"<br>\n      <br>\n      Wählen Sie in CV-Navi die Datei zum Update des PhoneControl. Der Dateiname beginnt mit <b>Control13-1</b><br>\n      <br>\n      Führen Sie das Update durch<br>\n      <br>\n      Danach die Verbindung zum EasyNet wieder trennen, die Jumper wieder umstecken und das Gehäuse wieder schließen.<br>\n    </p>\n  </body>\n</html>\n");
        jScrollPane2.setViewportView(jTextPane1);

        jBild1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBild2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBild1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBild2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(helpPCclose)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(helpPCclose))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBild1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBild2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpPCcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpPCcloseActionPerformed
        if( myParent != null ) {
            myParent.frameInstanceHelpPC = null;
        }
        this.dispose();
    }//GEN-LAST:event_helpPCcloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if( myParent != null ) {
            myParent.frameInstanceHelpPC = null;
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpPCclose;
    private javax.swing.JLabel jBild1;
    private javax.swing.JLabel jBild2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
