/*
 * HelpInfoLC.java
 *
 *
 * @author Kersten Tams Copyright 2009-2018
 * @author Lothar Roth  Copyright 2012-2018
 *
 */

package my.CVNavi;

/**
 *
 * @author lroth
 */
public class HelpInfoLC extends javax.swing.JDialog {

    private MC myParent = null;
    /**
     * Creates new form helpLokControl
     */
    public HelpInfoLC(MC parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if( parent == null ) {
            return;
        }
        if( parent.frameInstanceHelpLC != null ) {
            parent.frameInstanceHelpLC.toFront();
            parent.frameInstanceHelpLC.repaint();
            return;
        }
        parent.frameInstanceHelpLC = this;
        setLocationRelativeTo(parent);
        myParent = parent;

        // set to top to avoid scrolling to bottom
        this.jTextPane1.setCaretPosition(0);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpLCclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LokControl");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpLCclose.setText("Schließen");
        helpLCclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpLCcloseActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setText("<html>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>LokControl für Updates vorbereiten:</b><br>\n      <br>\n      Trennen Sie <b>alle</b> externen Steuergeräte vom EasyNet - einschließlich der LokControl, bei der Sie ein Update ausführen wollen.<br>\n      Drücken Sie dann gleichzeitig die Tasten [stop] und [go] an der LokControl und stellen Sie die Verbindung der LokControl zum EasyNet wieder her, während Sie die beiden Tasten gedrückt halten.<br>\n      Im Display der LokControl erscheint die Meldung \"Boot Loader\", die Versionsnummer des Boot Loaders (= Update-Programm) sowie die Versionsnummer der Hardware, z.B. \"HW = 13\".<br>\n      <br>\n      Wechseln Sie als nächstes an der MasterControl in den Menüpunkt \"Software-Update\" und bestätigen Sie die Auswahl mit [#] / ok.<br>\n      Im Display der MasterControl erscheint daraufhin in der unteren Zeile \"...Download...\"<br>\n      <br>\n      Wählen Sie in CV-Navi die Datei zum Update der LokControl. Der Dateiname beginnt mit <b>Control13-1</b> (Ausnahme -> \"Was ist Was ?\")\n    </p>\n  </body>\n</html>\n");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(helpLCclose)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpLCclose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpLCcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpLCcloseActionPerformed
        if( myParent != null ) {
            myParent.frameInstanceHelpLC = null;
        }
        this.dispose();
    }//GEN-LAST:event_helpLCcloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if( myParent != null ) {
            myParent.frameInstanceHelpLC = null;
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpLCclose;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
