/*
 * HelpInfoWasistWas.java
 *
 *
 * @author Kersten Tams Copyright 2009-2018
 * @author Lothar Roth  Copyright 2012-2018
 *
 */

package my.CVNavi;

/**
 *
 * @author lroth
 */
public class HelpInfoWasIstWas extends javax.swing.JDialog {

    private MC myParent = null;
    /**
     * Creates new form helpWasIstWas
     */
    public HelpInfoWasIstWas(MC parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if( parent == null ) {
            return;
        }
        if( parent.frameInstanceHelpWIW != null ) {
            parent.frameInstanceHelpWIW.toFront();
            parent.frameInstanceHelpWIW.repaint();
            return;
        }
        parent.frameInstanceHelpWIW = this;
        setLocationRelativeTo(parent);
        myParent = parent;

        // set to top to avoid scrolling to bottom
        this.jTextPane1.setCaretPosition(0);
        this.setResizable(true);
        this.pack();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpWIWclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Was ist Was (Dateinamen)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpWIWclose.setText("Schließen");
        helpWIWclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpWIWcloseActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("my/CVNavi/Bundle"); // NOI18N
        jTextPane1.setText(bundle.getString("HelpInfoWasIstWas.jTextPane1.text")); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(helpWIWclose)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpWIWclose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpWIWcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpWIWcloseActionPerformed
        if( myParent != null ) {
            myParent.frameInstanceHelpWIW = null;
        }
        this.dispose();
    }//GEN-LAST:event_helpWIWcloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if( myParent != null ) {
            myParent.frameInstanceHelpWIW = null;
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpWIWclose;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
