/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.KlarText;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author ktams
 */
public class FunktionsIcons extends javax.swing.JFrame {

    /**
     * Creates new form FunktionsIcons
     */
    
    public int DecAdress;
    public String DecName;
    public String DecIcons[];
    public MC KTUI;
    
    private String IconString;
    private String IconNames[];
    
    public FunktionsIcons() {
        this.IconNames = new String[]{};
        initComponents();
        setVisible(true);
    }

    FunktionsIcons(MC aThis) {
        this.IconNames = new String[]{
            "",
            "",
            "Stirnbeleuchtung",
            "Innenraumbeleuchtung",
            "Führerstandsbeleuchtung",
            "Fahrgeräusch (Motorgeräusch)",
            "Allgemeines Geräusch",
            "Bahnhofsdurchsage",
            "Rangiergang",
            "ABV (Anfahr/Bremszeit aus)",
            "Automatische Kupplung",
            "Rauchgenerator",
            "Panthograph",
            "Fernlicht",
            "Glocke",
            "Horn (Hupe)",
            "Pfeife",
            "Türen auf/zu",
            "Lüfter",
            "Kohle Schaufeln",
            "Erweiterungstaste (Shift)",
            "Zugzielanzeige",
            "Bremsenquitschen",
            "Kranarm heben/senken",
            "Kranhaken heben/senken",
            "Triebwerksbeleuchtung",
            "Kran drehen",
            "Dampf ablassen (Zylinderdampf)",
            "Betriebsfunk",
            "Kupplungsgeräusch",
            "Schienenstoß",
            "Diesel Fahrstufe Auf",
            "Diesel Fahrstufe Ab",
            "Schaffnerpfiff",
            "Pufferstoß",
            "Führerstandsbeleuchtung 2",
            "Wasser fassen (Dampflok)",
            "Kurvengeräusch",
            "Weichengeräusch",
            "Sicherheitsventil",
            "Ölbrenner",
            "Stoker",
            "Dynamische Bremse",
            "Kompressor",
            "Pressluft ablassen",
            "Handbremse",
            "Luftpumpe (Dampflok)",
            "Wasserpumpe (Dampflok)",
            "Hauptschalter (E-Lok)",
            "Ditchlight",
            "Marslight",
            "Gyralight",
            "Rule 17",
            "Rotary Beacon",
            "Feuerbüchse",
            "Ölkühler",
            "Sanden",
            "Abschlammen",
            "Bremse setzen (Lösen automatisch)",
            "Rangierbeleuchtung",
            "Führerpultbeleuchtung",
            "Injektor",
            "Hilfsdiesel",
            "Rücklicht rot",
            "Dopplereffekt",
            "Kurzpfiff",
            "Ölpumpe (Dampflok)",
            "Heizung",
            "Lichtmaschine (Dampflok)",
            "Dieselpumpe",
            "Fahrtrichtungsumschalter",
            "Hilfsluftpresser",
            "Vorschmieren",
            "Sifa-Meldung",
            "Schaltstufe (E-Lok)"
        };
        initComponents();
        KTUI = aThis;
        setLocationRelativeTo(aThis);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDecAdr = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jIconTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Funktions-Icons");

        jDecAdr.setText("Decoder Adress: ");

        jName.setText("Name:");

        jIconTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0), null, null},
                { new Integer(1), null, null},
                { new Integer(2), null, null},
                { new Integer(3), null, null},
                { new Integer(4), null, null},
                { new Integer(5), null, null},
                { new Integer(6), null, null},
                { new Integer(7), null, null},
                { new Integer(8), null, null},
                { new Integer(9), null, null},
                { new Integer(10), null, null},
                { new Integer(11), null, null},
                { new Integer(12), null, null},
                { new Integer(13), null, null},
                { new Integer(14), null, null},
                { new Integer(15), null, null},
                { new Integer(16), null, null},
                { new Integer(17), null, null},
                { new Integer(18), null, null},
                { new Integer(19), null, null},
                { new Integer(20), null, null},
                { new Integer(21), null, null},
                { new Integer(22), null, null},
                { new Integer(23), null, null},
                { new Integer(24), null, null},
                { new Integer(25), null, null},
                { new Integer(26), null, null},
                { new Integer(27), null, null},
                { new Integer(28), null, null},
                { new Integer(29), null, null},
                { new Integer(30), null, null},
                { new Integer(31), null, null},
                { new Integer(32), null, null}
            },
            new String [] {
                "Funktion", "Icon-No", "Beschreibung"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jIconTable.setRowHeight(20);
        jIconTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jIconTable);
        if (jIconTable.getColumnModel().getColumnCount() > 0) {
            jIconTable.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDecAdr)
                        .addGap(59, 59, 59)
                        .addComponent(jName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDecAdr)
                    .addComponent(jName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jIconTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);        
        TableColumn col = jIconTable.getColumnModel().getColumn(0);
        col.setPreferredWidth(60);
        col = jIconTable.getColumnModel().getColumn(1);
        col.setPreferredWidth(60);
        col = jIconTable.getColumnModel().getColumn(2);
        col.setPreferredWidth(jIconTable.getWidth() - 120);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jIconTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        jIconTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );

        for( int i = 0; i < DecIcons.length; i++)
        {
            IconString = null;
            String s = DecIcons[i].substring(0, DecIcons[i].indexOf(" "));
            try {
                int n = Integer.parseInt(s);
                if(n == DecAdress)
                {
                    IconString = DecIcons[i];
                    break;
                }
            } catch (NumberFormatException numberFormatException) {
            }
        }
        for(int i = 0; i < 33; i++)
        {
            jIconTable.setValueAt("---", i, 1);
        }
        if(IconString != null)
        {
            IconString = IconString.substring(IconString.indexOf(" ") + 1, IconString.length());
            while (IconString.length() > 2)
            {
                String s = IconString.substring(0, IconString.indexOf(","));
                int parseInt = 0;
                try {
                    parseInt = Integer.parseInt(s);
                    IconString = IconString.substring(IconString.indexOf(",") + 1, IconString.length());
                    int Index = 0;
                    Index = IconString.indexOf(" ");
                    int parseInt1 = 0;
                    if(Index != -1)
                    {
                        parseInt1 = Integer.parseInt(IconString.substring(0, Index));
                    }
                    else
                    {
                        parseInt1 = Integer.parseInt(IconString);
                    }
                    jIconTable.setValueAt(""+parseInt1, parseInt, 1);
                    jIconTable.setValueAt(IconNames[parseInt1], parseInt, 2);
                    IconString = IconString.substring(IconString.indexOf(" ")+1, IconString.length());
                } catch (NumberFormatException numberFormatException) {
                }
            }
        }
        jDecAdr.setText("Decoder Adr: " + DecAdress);
        jName.setText("Decoder Name: " + DecName);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunktionsIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunktionsIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunktionsIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunktionsIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunktionsIcons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jDecAdr;
    private javax.swing.JTable jIconTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jName;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
