package my.KlarText;

import javax.swing.ImageIcon;

/**
 *
 * @author lroth
 */
public class HelpInfoMC extends javax.swing.JDialog {

    private MC myParent = null;
    /**
     * Creates new form helpMControl
     */
    public HelpInfoMC(MC parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if( parent == null ) {
            return;
        }
        if( parent.frameInstanceHelpMC != null ) {
            parent.frameInstanceHelpMC.toFront();
            parent.frameInstanceHelpMC.repaint();
            return;
        }
        parent.frameInstanceHelpMC = this;
        setLocationRelativeTo(parent);
        myParent = parent;

        // set to top to avoid scrolling to bottom
        this.jTextPane1.setCaretPosition(0);

        ImageIcon Img1 = new ImageIcon(getClass().getResource("/Update_mControl_small.png"));
        jBild1.setIcon(Img1);
        pack();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpMCclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jBild1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HandControl");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        helpMCclose.setText("Schließen");
        helpMCclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMCcloseActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setText("<html>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>HandControl für Updates vorbereiten:</b><br>\n      <br>\n      Trennen Sie die Verbindungen zwischen mControl und Spannungsversorgung (Stecker-Netzteil).<br>\n      Trennen Sie <b>alle</b> externen Steuergeräte vom EasyNet - einschließlich der mControl, bei der Sie ein Update ausführen wollen.<br>\n      Schrauben Sie den Gehäusedeckel ab.<br>\n      Überbrücken Sie die Pins der Stiftleiste (siehe Zeichnung). Verwenden Sie dazu vorzugsweise den Jumper, der im Auslieferungszustand auf einem der Pins aufgesteckt ist.<br>\n      Stellen Sie die Verbindungen zwischen mControl und Spannungsversorgung (Stecker-Netzteil) wieder her.<br>\n      Stellen Sie die Verbindungen zwischen EasyNet und mControl wieder her. → Die LED auf der mControl blinkt rot und zeigt damit an, dass sich das Gerät im Update-Modus befindet.<br>\n      Wechseln Sie als nächstes an der MasterControl in den Menüpunkt \"Software-Update\" und bestätigen Sie die Auswahl mit [#] / ok.<br>\n      Im Display der MasterControl erscheint daraufhin in der unteren Zeile \"...Download...\"<br>\n      <br>\n      Wählen Sie in CV-Navi die Datei zum Update der mControl. Der Dateiname beginnt mit <b>mControl</b>\n      <br>\n      Danach die Verbindung zur Spannungsversorgung und zum EasyNet wieder trennen, die Jumper wieder umstecken und das Gehäuse wieder aufschrauben.<br>\n      Stellen Sie alle Verbindungen, die zum Betrieb notwendig sind, wieder her. <br>\n    </p>\n </body>\n</html>\n");
        jScrollPane2.setViewportView(jTextPane1);

        jBild1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBild1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpMCclose)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpMCclose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBild1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpMCcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMCcloseActionPerformed
        if( myParent != null ) {
            myParent.frameInstanceHelpMC = null;
        }
        this.dispose();
    }//GEN-LAST:event_helpMCcloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if( myParent != null ) {
            myParent.frameInstanceHelpMC = null;
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpMCclose;
    private javax.swing.JLabel jBild1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
