/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.KlarText;

import javax.swing.ImageIcon;

/**
 *
 * @author ktams
 */
public class MultiDec extends javax.swing.JFrame {

    public KlarTextUI KTUI;
    /**
     * Creates new form MultiDec
     */
    public MultiDec() {
        initComponents();
    }

    MultiDec(KlarTextUI ktuiThis) {
        if( ktuiThis == null ) {
            return;
        }
        KTUI = ktuiThis;
        if( KTUI.frameInstanceDEVICE != null ) {
            KTUI.frameInstanceDEVICE.toFront();
            KTUI.frameInstanceDEVICE.repaint();
            return;
        }
        initComponents();
        ImageIcon II = null;
        II = new ImageIcon(getClass().getResource("/WD-34.gif"));
        jBild.setIcon(II);
        setTitle( KTUI.getMenutext( decoderList.MultiDecoder ).trim() );
        this.setIconImage(II.getImage());

        setLocationRelativeTo(ktuiThis);
        setVisible(true);
        KTUI.frameInstanceDEVICE = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jExit = new javax.swing.JButton();
        jBild = new javax.swing.JLabel();
        jRead = new javax.swing.JButton();
        jWrite = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jMode1 = new javax.swing.JRadioButton();
        jMode2 = new javax.swing.JRadioButton();
        jMode3 = new javax.swing.JRadioButton();
        jMode4 = new javax.swing.JRadioButton();
        jMode5 = new javax.swing.JRadioButton();
        jMode6 = new javax.swing.JRadioButton();
        jModeLabel = new javax.swing.JLabel();
        jRC_on = new javax.swing.JCheckBox();
        jCh1 = new javax.swing.JCheckBox();
        jCH2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jVersion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jOntimeLabel1 = new javax.swing.JLabel();
        jOntimeLabel2 = new javax.swing.JLabel();
        jOntimeLabel3 = new javax.swing.JLabel();
        jOntimeLabel4 = new javax.swing.JLabel();
        jOnTime4 = new javax.swing.JTextField();
        jOnTime1 = new javax.swing.JTextField();
        jOnTime2 = new javax.swing.JTextField();
        jOnTime3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jOnTime5 = new javax.swing.JTextField();
        jOnTime6 = new javax.swing.JTextField();
        jOnTime7 = new javax.swing.JTextField();
        jOnTime8 = new javax.swing.JTextField();
        jPaired1 = new javax.swing.JCheckBox();
        jPaired2 = new javax.swing.JCheckBox();
        jPaired3 = new javax.swing.JCheckBox();
        jPaired4 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLimitStop1 = new javax.swing.JCheckBox();
        jLimitStop2 = new javax.swing.JCheckBox();
        jLimitStop3 = new javax.swing.JCheckBox();
        jLimitStop4 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jServoSpeed1 = new javax.swing.JTextField();
        jServoPosL1 = new javax.swing.JTextField();
        jServoPosR1 = new javax.swing.JTextField();
        jServoPosR2 = new javax.swing.JTextField();
        jServoPosL2 = new javax.swing.JTextField();
        jServoSpeed2 = new javax.swing.JTextField();
        jServoPosL3 = new javax.swing.JTextField();
        jServoPosR3 = new javax.swing.JTextField();
        jServoSpeed3 = new javax.swing.JTextField();
        jServoPosL4 = new javax.swing.JTextField();
        jServoPosR4 = new javax.swing.JTextField();
        jServoSpeed4 = new javax.swing.JTextField();
        jServoPosL5 = new javax.swing.JTextField();
        jServoPosR5 = new javax.swing.JTextField();
        jServoSpeed5 = new javax.swing.JTextField();
        jServoSpeed6 = new javax.swing.JTextField();
        jServoPosL6 = new javax.swing.JTextField();
        jServoPosR6 = new javax.swing.JTextField();
        jServoPosR7 = new javax.swing.JTextField();
        jServoSpeed7 = new javax.swing.JTextField();
        jServoPosR8 = new javax.swing.JTextField();
        jServoPosL7 = new javax.swing.JTextField();
        jServoSpeed8 = new javax.swing.JTextField();
        jServoPosL8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jControlOff1 = new javax.swing.JCheckBox();
        jControlOff2 = new javax.swing.JCheckBox();
        jControlOff3 = new javax.swing.JCheckBox();
        jControlOff4 = new javax.swing.JCheckBox();
        jControlOff5 = new javax.swing.JCheckBox();
        jControlOff6 = new javax.swing.JCheckBox();
        jControlOff7 = new javax.swing.JCheckBox();
        jControlOff8 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setText("Close");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 121, -1));
        getContentPane().add(jBild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 192, 120));

        jRead.setText("Read");
        getContentPane().add(jRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 120, -1));

        jWrite.setText("Write");
        getContentPane().add(jWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 120, -1));

        jButton1.setText("Cancel");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 120, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jMode1);
        jMode1.setSelected(true);
        jMode1.setText("1: 4 turn outs + LED to show the position");
        jMode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode1ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup1.add(jMode2);
        jMode2.setText("2: 4 turn outs + buttons");
        jMode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode2ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        buttonGroup1.add(jMode3);
        jMode3.setText("3: 4 turn outs + 8 servos");
        jMode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode3ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        buttonGroup1.add(jMode4);
        jMode4.setText("4: 8 servos + buttons");
        jMode4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode4ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        buttonGroup1.add(jMode5);
        jMode5.setText("5: 8 servos + polarization");
        jMode5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode5ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup1.add(jMode6);
        jMode6.setText("6: 8 servos + switches");
        jMode6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMode6ActionPerformed(evt);
            }
        });
        jPanel1.add(jMode6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jModeLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mode"));
        jPanel1.add(jModeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 150));

        jRC_on.setSelected(true);
        jRC_on.setText("on");
        jPanel1.add(jRC_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jCh1.setSelected(true);
        jCh1.setText("Channel 1");
        jPanel1.add(jCh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jCH2.setSelected(true);
        jCH2.setText("Channel 2");
        jPanel1.add(jCH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("RailCom"));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, 90));

        jVersion.setText("Version: 1.0.0 ");
        jPanel1.add(jVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jOntimeLabel1.setText("On Time point 1:");
        jPanel2.add(jOntimeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jOntimeLabel2.setText("On Time point 1:");
        jPanel2.add(jOntimeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jOntimeLabel3.setText("On Time point 1:");
        jPanel2.add(jOntimeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jOntimeLabel4.setText("On Time point 1:");
        jPanel2.add(jOntimeLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jOnTime4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime4.setText("5");
        jPanel2.add(jOnTime4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, -1));

        jOnTime1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime1.setText("5");
        jPanel2.add(jOnTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, -1));

        jOnTime2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime2.setText("5");
        jPanel2.add(jOnTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, -1));

        jOnTime3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime3.setText("5");
        jPanel2.add(jOnTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("On Time r / g"));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 110));

        jOnTime5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime5.setText("5");
        jPanel2.add(jOnTime5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jOnTime6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime6.setText("5");
        jPanel2.add(jOnTime6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 40, -1));

        jOnTime7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime7.setText("5");
        jPanel2.add(jOnTime7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 40, -1));

        jOnTime8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnTime8.setText("5");
        jPanel2.add(jOnTime8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, -1));

        jPaired1.setSelected(true);
        jPaired1.setText("paired");
        jPanel2.add(jPaired1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jPaired2.setSelected(true);
        jPaired2.setText("paired");
        jPanel2.add(jPaired2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jPaired3.setSelected(true);
        jPaired3.setText("paired");
        jPanel2.add(jPaired3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jPaired4.setSelected(true);
        jPaired4.setText("paired");
        jPanel2.add(jPaired4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel3.setText("Point 4");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel4.setText("Point 1");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel5.setText("Point 2");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel6.setText("Point 3");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Switch mode"));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 110));

        jLimitStop1.setText("yes");
        jPanel2.add(jLimitStop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLimitStop2.setText("yes");
        jPanel2.add(jLimitStop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLimitStop3.setText("yes");
        jPanel2.add(jLimitStop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLimitStop4.setText("yes");
        jPanel2.add(jLimitStop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Limit stop"));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 110));

        jLabel9.setText("Point 1");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 20));

        jLabel10.setText("Point 2");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 20));

        jLabel11.setText("Point 3");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 20));

        jLabel12.setText("Point 4");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 20));

        jTabbedPane1.addTab("Outputs", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Servo 8");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel14.setText("Servo 1");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel15.setText("Servo 2");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel16.setText("Servo 3");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel17.setText("Servo 4");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel19.setText("Servo 5");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel20.setText("Servo 6");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel21.setText("Servo 7");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel18.setText("Position l");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel22.setText("Control in rest");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel23.setText("Position r");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jServoSpeed1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed1.setText("16");
        jPanel3.add(jServoSpeed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 60, -1));

        jServoPosL1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL1.setText("1400");
        jPanel3.add(jServoPosL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, -1));

        jServoPosR1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR1.setText("1600");
        jPanel3.add(jServoPosR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));

        jServoPosR2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR2.setText("1600");
        jPanel3.add(jServoPosR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, -1));

        jServoPosL2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL2.setText("1400");
        jPanel3.add(jServoPosL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, -1));

        jServoSpeed2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed2.setText("16");
        jPanel3.add(jServoSpeed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, -1));

        jServoPosL3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL3.setText("1400");
        jPanel3.add(jServoPosL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        jServoPosR3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR3.setText("1600");
        jPanel3.add(jServoPosR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 60, -1));

        jServoSpeed3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed3.setText("16");
        jPanel3.add(jServoSpeed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 60, -1));

        jServoPosL4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL4.setText("1400");
        jPanel3.add(jServoPosL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, -1));

        jServoPosR4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR4.setText("1600");
        jPanel3.add(jServoPosR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, -1));

        jServoSpeed4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed4.setText("16");
        jPanel3.add(jServoSpeed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, -1));

        jServoPosL5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL5.setText("1400");
        jPanel3.add(jServoPosL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, -1));

        jServoPosR5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR5.setText("1600");
        jPanel3.add(jServoPosR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, -1));

        jServoSpeed5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed5.setText("16");
        jPanel3.add(jServoSpeed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, -1));

        jServoSpeed6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed6.setText("16");
        jPanel3.add(jServoSpeed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 60, -1));

        jServoPosL6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL6.setText("1400");
        jPanel3.add(jServoPosL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));

        jServoPosR6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR6.setText("1600");
        jPanel3.add(jServoPosR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, -1));

        jServoPosR7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR7.setText("1600");
        jPanel3.add(jServoPosR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, -1));

        jServoSpeed7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed7.setText("16");
        jPanel3.add(jServoSpeed7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 60, -1));

        jServoPosR8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosR8.setText("1600");
        jPanel3.add(jServoPosR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

        jServoPosL7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL7.setText("1400");
        jPanel3.add(jServoPosL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, -1));

        jServoSpeed8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoSpeed8.setText("16");
        jPanel3.add(jServoSpeed8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, -1));

        jServoPosL8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServoPosL8.setText("1400");
        jPanel3.add(jServoPosL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, -1));

        jLabel24.setText("Speed");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jControlOff1.setText("off");
        jPanel3.add(jControlOff1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jControlOff2.setText("off");
        jPanel3.add(jControlOff2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jControlOff3.setText("off");
        jPanel3.add(jControlOff3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jControlOff4.setText("off");
        jPanel3.add(jControlOff4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jControlOff5.setText("off");
        jPanel3.add(jControlOff5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jControlOff6.setText("off");
        jPanel3.add(jControlOff6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jControlOff7.setText("off");
        jPanel3.add(jControlOff7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jControlOff8.setText("off");
        jPanel3.add(jControlOff8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel25.setText("Follow up time:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 20));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("255");
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 40, -1));

        jLabel26.setText("x100 msec");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 20));

        jTabbedPane1.addTab("Servos", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        dispose();
    }//GEN-LAST:event_jExitActionPerformed

    private void jMode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode1ActionPerformed

    private void jMode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode2ActionPerformed

    private void jMode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode3ActionPerformed

    private void jMode4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode4ActionPerformed

    private void jMode5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode5ActionPerformed

    private void jMode6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMode6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMode6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiDec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiDec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiDec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiDec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiDec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jBild;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCH2;
    private javax.swing.JCheckBox jCh1;
    private javax.swing.JCheckBox jControlOff1;
    private javax.swing.JCheckBox jControlOff2;
    private javax.swing.JCheckBox jControlOff3;
    private javax.swing.JCheckBox jControlOff4;
    private javax.swing.JCheckBox jControlOff5;
    private javax.swing.JCheckBox jControlOff6;
    private javax.swing.JCheckBox jControlOff7;
    private javax.swing.JCheckBox jControlOff8;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jLimitStop1;
    private javax.swing.JCheckBox jLimitStop2;
    private javax.swing.JCheckBox jLimitStop3;
    private javax.swing.JCheckBox jLimitStop4;
    private javax.swing.JRadioButton jMode1;
    private javax.swing.JRadioButton jMode2;
    private javax.swing.JRadioButton jMode3;
    private javax.swing.JRadioButton jMode4;
    private javax.swing.JRadioButton jMode5;
    private javax.swing.JRadioButton jMode6;
    private javax.swing.JLabel jModeLabel;
    private javax.swing.JTextField jOnTime1;
    private javax.swing.JTextField jOnTime2;
    private javax.swing.JTextField jOnTime3;
    private javax.swing.JTextField jOnTime4;
    private javax.swing.JTextField jOnTime5;
    private javax.swing.JTextField jOnTime6;
    private javax.swing.JTextField jOnTime7;
    private javax.swing.JTextField jOnTime8;
    private javax.swing.JLabel jOntimeLabel1;
    private javax.swing.JLabel jOntimeLabel2;
    private javax.swing.JLabel jOntimeLabel3;
    private javax.swing.JLabel jOntimeLabel4;
    private javax.swing.JCheckBox jPaired1;
    private javax.swing.JCheckBox jPaired2;
    private javax.swing.JCheckBox jPaired3;
    private javax.swing.JCheckBox jPaired4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jRC_on;
    private javax.swing.JButton jRead;
    private javax.swing.JTextField jServoPosL1;
    private javax.swing.JTextField jServoPosL2;
    private javax.swing.JTextField jServoPosL3;
    private javax.swing.JTextField jServoPosL4;
    private javax.swing.JTextField jServoPosL5;
    private javax.swing.JTextField jServoPosL6;
    private javax.swing.JTextField jServoPosL7;
    private javax.swing.JTextField jServoPosL8;
    private javax.swing.JTextField jServoPosR1;
    private javax.swing.JTextField jServoPosR2;
    private javax.swing.JTextField jServoPosR3;
    private javax.swing.JTextField jServoPosR4;
    private javax.swing.JTextField jServoPosR5;
    private javax.swing.JTextField jServoPosR6;
    private javax.swing.JTextField jServoPosR7;
    private javax.swing.JTextField jServoPosR8;
    private javax.swing.JTextField jServoSpeed1;
    private javax.swing.JTextField jServoSpeed2;
    private javax.swing.JTextField jServoSpeed3;
    private javax.swing.JTextField jServoSpeed4;
    private javax.swing.JTextField jServoSpeed5;
    private javax.swing.JTextField jServoSpeed6;
    private javax.swing.JTextField jServoSpeed7;
    private javax.swing.JTextField jServoSpeed8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jVersion;
    private javax.swing.JButton jWrite;
    // End of variables declaration//GEN-END:variables
}
